export const EXERCISES: Record<string, string[]> = {
  "Squat": [
    "Back Squat",
    "Front Squat",
    "Goblet Squat",
    "Box Squat",
    "Pause Squat",
    "Safety Bar Squat",
    "Bulgarian Split Squat",
    "Hack Squat",
    "Zercher Squat",
  ],
  "Hinge": [
    "Conventional Deadlift",
    "Sumo Deadlift",
    "Romanian Deadlift",
    "Stiff-Leg Deadlift",
    "Trap Bar Deadlift",
    "Good Morning",
    "Hip Thrust",
    "Glute Bridge",
    "Kettlebell Swing",
  ],
  "Press": [
    "Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Overhead Press",
    "Push Press",
    "Dumbbell Bench Press",
    "Dumbbell Overhead Press",
    "Dips",
    "Floor Press",
    "Close-Grip Bench Press",
  ],
  "Pull": [
    "Pull-Up",
    "Chin-Up",
    "Barbell Row",
    "Pendlay Row",
    "Dumbbell Row",
    "Cable Row",
    "Lat Pulldown",
    "Face Pull",
    "Shrug",
    "T-Bar Row",
  ],
  "Carry & Core": [
    "Farmer Carry",
    "Suitcase Carry",
    "Plank",
    "Ab Wheel Rollout",
    "Hanging Leg Raise",
    "Cable Crunch",
    "Pallof Press",
    "Suitcase Deadlift",
  ],
  "Arms": [
    "Barbell Curl",
    "Dumbbell Curl",
    "Hammer Curl",
    "Preacher Curl",
    "Tricep Pushdown",
    "Skull Crusher",
    "Overhead Tricep Extension",
    "Dumbbell Kickback",
  ],
  "Legs (Isolation)": [
    "Leg Press",
    "Leg Curl",
    "Leg Extension",
    "Calf Raise",
    "Seated Calf Raise",
    "Nordic Curl",
    "Reverse Hyper",
  ],
  "Cardio & Conditioning": [
    "Sled Push",
    "Sled Pull",
    "Battle Ropes",
    "Box Jump",
    "Assault Bike",
    "Row Machine",
    "Running",
    "Jump Rope",
  ],
};

export const ALL_EXERCISES = Object.values(EXERCISES).flat().sort();
